{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{def $handler_id = $handler.id_string}

{* Modifico il nome dell'handler se ezcollaboration, prob bug di ez. Vedi notificationevent.php *}
{if $handler.id_string|eq('ezcollaboration')}
    {set $handler_id = 'ezcollaborationnotification'}
{/if}

{let  handler_items=fetch(notification,digest_items,hash(date,$date.timestamp,address,$address,handler,$handler_id))}
  {section name=Items loop=$handler_items}
    {append-block scope=global variable=collection_item_id_list}{$Items:item.id}{/append-block}
    {include handler=$handler collection_item=$Items:item uri=concat( "design:notification/handler/",$handler.id_string,"/view/digest_element_plain.tpl")}


  {/section}
{/let}

{undef $handler_id}
