<?php /* #?ini charset="utf-8"?

[FieldSettings]
FieldConnectors[user/user_account]=UserAccountFieldConnector
FieldConnectors[sensor_operator/account]=UserAccountFieldConnector
FieldConnectors[sensor_scenario/triggers]=SensorScenarioTriggerFieldConnector
FieldConnectors[sensor_scenario/criterion_type]=SensorScenarioCriterionTypeFieldConnector
FieldConnectors[sensor_scenario/owner]=SensorScenarioOwnerFieldConnector
FieldConnectors[sensor_scenario/observer]=SensorScenarioObserverFieldConnector
FieldConnectors[sensor_faq/answer]=\Opencontent\Ocopendata\Forms\Connectors\OpendataConnector\FieldConnector\EzOnlineEditorXmlField
FieldConnectors[sensor_report/intro]=\Opencontent\Ocopendata\Forms\Connectors\OpendataConnector\FieldConnector\EzOnlineEditorXmlField
FieldConnectors[sensor_report_item/text]=\Opencontent\Ocopendata\Forms\Connectors\OpendataConnector\FieldConnector\EzOnlineEditorXmlField

[ClassSettings]
ClassConnectors[sensor_scenario]=SensorScenarioClassConnector
ClassConnectors[sensor_report]=SensorReportClassConnector
ClassConnectors[sensor_report_item]=SensorReportItemClassConnector
ClassConnectors[user_group]=UserGroupClassConnector
